{{- if and .Values.credentials.key .Values.credentials.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webhookrelay-operator.fullname" . }}-operator
  labels:
    name: {{ template "webhookrelay-operator.name" . }}-operator
{{ include "webhookrelay-operator.labels" . | indent 4 }}
type: Opaque
stringData:
  key: {{ .Values.credentials.key }}
  secret: {{ .Values.credentials.secret }}
{{- end }}
