{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "webhookrelay-operator.fullname" . }}-operator
  labels:
    name: {{ template "webhookrelay-operator.name" . }}-operator
{{ include "webhookrelay-operator.labels" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ template "webhookrelay-operator.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "webhookrelay-operator.serviceAccountName" . }}
{{- end }}
