apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webhookrelayforwards.forward.webhookrelay.com
spec:
  group: forward.webhookrelay.com
  names:
    kind: WebhookRelayForward
    listKind: WebhookRelayForwardList
    plural: webhookrelayforwards
    singular: webhookrelayforward
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: WebhookRelayForward is the Schema for the webhookrelayforwards
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WebhookRelayForwardSpec defines the desired state of WebhookRelayForward
            type: object
          status:
            description: WebhookRelayForwardStatus defines the observed state of WebhookRelayForward
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
