apiVersion: forward.webhookrelay.com/v1
kind: WebhookRelayForward
metadata:
  name: example-webhookrelayforward
spec:
  # Add fields here
  secretRefName: whr-credentials
  secretRefNamespace: ""
  buckets:
    - ref: k8s-operator
      

