apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookrelay-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webhookrelay-operator
  template:
    metadata:
      labels:
        name: webhookrelay-operator
    spec:
      serviceAccountName: webhookrelay-operator
      containers:
        - name: webhookrelay-operator
          # Replace this with the built image name
          image: webhookrelay/webhookrelay-operator:latest
          command:
          - webhookrelay-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "webhookrelay-operator"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi